title: Haringey Association of Neighbourhood Watches (HANHW) 
email: admin@haringeynhw.org.uk 
description: The Haringey Association of Neighbourhood Watches provides information for all the Neighbourhood Watches in Haringey.
baseurl: "/"
url: "https://mrded.github.io/hanhw"
theme: minima
plugins:
  - jekyll-feed
collections:
  scams:
    output: true
